# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aa5b4043b80216dc3e1f244030bfc2975c29308ee150f1e1b661221c8d5c48ef98218020b0ac74baa18897d1af4b7ac56d76d2ceeed651250e18dd3936209321

test:
  secret_key_base: 5f121f42a914829514f6256ab3ce1fb5dc002c767793a1dcdfee4ff01089a04de5dbf1436736262bdbd665d866e1e7acf19a81d918c84905d70a4f4617378290

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
